### ISSUE TITLE
Enhancement: Optional Item Kit Combo Mode

### ISSUE THREAD

**Issue by darkshade9** [Raptor007/aq2-tng#136]
Proposal to include a server cvar (for example, `kit_mode`), which is a toggle [0/1], where 1 enables Item Kit mode.

Item Kit mode combines items into kits, so they become more useful versus using the Kevlar Vest.  Data shows that the Kevlar Vest is used more than 3/4 of all item selections combined (60k+ samples), and we'd like to get a little more parity among the other items, to give games a bit more variety.

Item Kits proposed:

```
Commando Kit:  Bandolier + Kevlar Helmet
Stealth Kit: Stealth Slippers + Silencer
Assassin Kit: Laser Sight + Silencer
```

The Item list would show like so if this mode is enabled:
```
Kevlar Vest
Commando Kit (Bandolier + Kevlar Helm)
Stealth Kit (Slippers + Silencer)
Assassin Kit (Laser Sight + Silencer)
```
Trello card: https://trello.com/c/4SC6nJbP

![image](https://user-images.githubusercontent.com/1392336/191363947-7c892b92-7df1-4cc7-b57a-2a043d18bf65.png)

**Comment by MVarland** [comment]
Currently if you're playing Bandolier and want to use your grenade right after ACTION! You're essentially useless in the beginning. Since you cannot pull the pin and throw until the announcer yells ACTION! 

To make the grenade(s) a bit more tactical/useful it would be cool if it was possible to pull the pin a bit earlier like when the announcer yells LIGHTS...

Seeing a grenade coming at you or on the floor just at the ACTION! Announcement would probably make players stop and wait until it has detonated. This could be a gamechanger for that specific round!

**Comment by darkshade9** [comment]
> Currently if you're playing Bandolier and want to use your grenade right after ACTION! You're essentially useless in the beginning. Since you cannot pull the pin and throw until the announcer yells ACTION!
> 
> To make the grenade(s) a bit more tactical/useful it would be cool if it was possible to pull the pin a bit earlier like when the announcer yells LIGHTS...
> 
> Seeing a grenade coming at you or on the floor just at the ACTION! Announcement would probably make players stop and wait until it has detonated. This could be a gamechanger for that specific round!

This is a good idea, might be its own enhancement ticket?  I assume the pin-pulling aspect of grenades during LCA is tied to the animation of the action, pin-pulling = pulling gun trigger.  If there's a way to adjust is so it's on the _throwing_ aspect of the grenade as opposed to the pin-pull, could be relatively easy?

**Comment by Raptor007** [comment]
Created issue #143 for grenade pin pull during LCA.  Good idea!

**Comment by darkshade9** [comment]
Item kit mode is live, tested working in https://github.com/actionquake/aq2-tng/, closing issue
