### ISSUE TITLE
Footstep sounds when walking

### ISSUE THREAD

**Issue by dynamic0** [Raptor007/aq2-tng#72]
Related to last issue...

When cl_run is set to 1 and the player uses command +speed, it makes the player to move slowly without making footstep sounds. However, if the player would strafe even a little bit, a sound is produced. Is it possible/good idea to make player movements silent, when walking? Excluding falling, jumping or sliding on slopes.

**Comment by stan0x** [comment]
+speed makes sounds when strafe since 1998. sv_silentwalk 1|0 would be a good option to build so server admins can make a choice if they want it enable or not. should be 0 by default if u ask me.

**Comment by dynamic0** [comment]
Sounds reasonable.

**Comment by Raptor007** [comment]
https://github.com/Raptor007/aq2-tng/blob/742044566591f26637876e5a3e467085a555e18e/source/p_view.c#L986-L991

Walk speed is 200, so the diagonal speed is about 283 when you walk forward and strafe at the same time.  I think `silentwalk` could just change the footstep threshold from xyspeed 225 to 285.  I also agree that this should be off by default because the old behavior makes stealth slippers more useful.

**Comment by Raptor007** [comment]
https://github.com/Raptor007/aq2-tng/commit/cc28d78b074df68dfa7f90825e2d0445c55aaf65
