### ISSUE TITLE
chasecam viewangle

### ISSUE THREAD

**Issue by m4son** [Raptor007/aq2-tng#77]
When leaving chasecam, spectators previous angle is restored instead of last player chased angle.

**Comment by Raptor007** [comment]
I think this is the same as bug #24.  I should take another crack at solving it.

**Comment by m4son** [comment]
Another thing that might be related to this problem is when spectating in any mode, players frags at right-top corner are not updated.

**Comment by m4son** [comment]
After some time testing, this commit from maniac, broke viewangles when leaving chasecam 
https://github.com/aq2-tng/aq2-tng/commit/1f2ab927a61a1669996a858eda07d0c874fd0484#diff-d28e9c6c4bd174fbd6765f4e4b8acc95
Please look, it is a really annoying thing.

**Comment by Raptor007** [comment]
Thanks for tracking this down.  I have a hunch it's because he moved a bunch of code in UpdateChaseCam into the `if (!(game.serverfeatures & GMF_CLIENTNUM))` block, which I don't think would be true on any modern q2pro server.  For example, `chase_mode == 2` previously considered `delta_angles` and it no longer does.

Leaving this "before" version as a reminder for myself: https://github.com/aq2-tng/aq2-tng/blob/b5e077d6bff051c1c54542f106e1ebd6bd828810/source/g_chase.c

**Comment by Raptor007** [comment]
This might be solved now: https://github.com/Raptor007/aq2-tng/commit/103580106e3345604af26e3243d0418efeb33953
